### ISSUE TITLE
Tweak to template

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connectomics_import#2]
The original template spec had some errors.  Template should look like this:

ID | TYPE | FACT | Weight
-- | -- | -- | --
ID | TYPE | I 'synapsed to' | >AT n2o:weight^^xsd:integer
VFB:jrchjsrm | owl:NamedIndividual | VFB:jrchjtex | 3
VFB:jrchjsrm | owl:NamedIndividual | VFB:jrchk5s8 | 5

Note -  changes to row2 + new column.

**Comment by admclachlan** [comment]
Adding the Type column will push the robot template tsv file size over the 100Mb limit on github. I could work out how many rows fit in the limit and split files automatically, or gzip files?

**Comment by dosumis** [comment]
Don't worry about it. We won't be posting to GitHub.  This will run on Jenkins, which will also move output files to the appropriate place.

**Comment by admclachlan** [comment]
addressed in 97e2c92d603774206f86cd44645b1c10403eb480
