### ISSUE TITLE
Apply thresholding to filter synaptic connections for loading

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_connectomics_import#3]
In discussion during Monday's call, we agree that we should at least filter out singleton synaptic connections between neurons.   Thereshold should be configurable by argument to the Python lib (perhaps with default =1) and by command line argument (optional?) to the runner script.

**Comment by admclachlan** [comment]
addressed in 264851e3f6b604a0675c5c33e50ed5be178f4932

Currently, threshold arg sets cutoff as less than or equal to the integer entered and the default is 1.
