### ISSUE TITLE
Look into Hemibrain v1.2

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/VFB_connectomics_import#9]

**Comment by Clare72** [comment]
https://docs.google.com/document/d/1vae3ClHR8z8uekqwrOHtqiux3oY5-Y_xw6W2srCi3PI/edit

Mostly mitochondrial detail added
There may be some new individuals added to OCG, LC and PN types (last bullet)

**Comment by admclachlan** [comment]
Using query "MATCH (n:Neuron) WHERE exists(n.type) return n.bodyId, n.instance, n.statusLabel, n.cropped" (only neuprint neurons with types), there were 22593 neurons in 1.1. In 1.2 there are 22704.

**Comment by Clare72** [comment]
Some typing has changed:
https://github.com/VirtualFlyBrain/hemibrain_metadata/blob/master/v1-1_to_v1-2_typing_changes.tsv

new types: 'LC33a', 'LC33b', 'OCG09', 'TRN_VP3a', 'TRN_VP3b'
removed types: 'LC33', 'TRN_VP3'

**Comment by Clare72** [comment]
112 new neurons (those with no type in 1.1)
1 removed neuron - 546303917 (no type in 1.2)

**Comment by admclachlan** [comment]
The typing changes match the 111 extra neurons in 1.2 vs 1.1. It looks like there are no other changes relevant to VFB so may not be necessary to reload everything? Will check if minimal metadata and connectivity is the same between 1.1 to 1.2 (except the new neurons) to determine if any other metadata will need updating.

**Comment by Clare72** [comment]
are we going to have a new dataset for 1.2?
